### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by glebmachine** [wagerfield/parallax#111] opened 2014-12-04 23:02 UTC
It would be great, if you add destroy method (with complete styles reset)
Keep forced layouts on disabled instances is not an option for huge pages with multiple scenes(

I've got few perfomance expirements, but still can't fix all stuff

**Comment by CHEWX** [comment] 2016-03-14 17:43
I guess this hasn't happened ?

**Comment by glebmachine** [comment] 2016-03-15 11:50
No, still have no news)

**Comment by RRorg** [comment] 2017-01-20 15:57
duplicate of #88

**Closed by RRorg** 2017-01-20 15:57 UTC
