### ISSUE TITLE
Prevent cursor detection beyond container.

### ISSUE THREAD

**Issue by ClarusDignus** [wagerfield/parallax#122] opened 2015-03-31 20:10 UTC
For context, I'm using Parallax.js as a jQuery plugin.

Is it possible to trigger the parallax effect ONLY when the container is moused over?

I've noticed the relative/clip parameters but if I'm to the left/right of my container, the up/down is still detected and reacted to. Equally, if I'm outside of the top/bottom of the container, left/right is detected and reacted to.

Naturally, my question only relates to cursor movements.

**Comment by newelement** [comment] 2015-06-10 14:45
+1

**Comment by RRorg** [comment] 2017-01-20 16:10
duplicate of #85

**Closed by RRorg** 2017-01-20 16:10 UTC
