### ISSUE TITLE
Layers fly away on mobile

### ISSUE THREAD

**Issue by lexleo** [wagerfield/parallax#235] opened 2017-12-02 09:02 UTC
On mobile both on iOS and Android parallax layers start to move down, then they reach some limit and fly away or bounce. It happens even if I hardly limit Y motion with 'limitY: 0'. On desktop it stops motion, but with gyroscope seems not. 

My demo here: https://lexleo.github.io/parallax/
The same we can see on mobile on parallax.js page: http://matthew.wagerfield.com/parallax/

when we sink into the water if we shift down. It's not so big deal in that case, but on my parallax it is critical, because I have no cover background to optimize parallax total size and parts break apart.

Could someone, please, give advice - is it kind of bug or I'am doing somewhing wrong?!
PS. Oh, thanks for the great lib anyway! :)

**Comment by reneroth** [comment] 2018-01-18 23:15
Did you fix the problem in the meantime? I can't reproduce it right now with my Android.

Pretty cool demo btw!

**Comment by lexleo** [comment] 2018-01-21 17:42
Thanks! No, unfortunately, I don't know how to, so it's still there.

**Comment by lexxwork** [comment] 2021-03-12 09:21
[https://i.imgur.com/a0EZeqT.png]()
it happens when do fast rotate along x axis about 30-50 degree and stop

**Comment by reneroth** [comment] 2024-04-06 08:00
duplicate of #249 (other way around to be precise, but closing this one)

**Closed by reneroth** 2024-04-06 08:00 UTC
Labels: support
